---
title: "SchoolFinder_Sports"
author: "Ken Powers"
date: "`r Sys.Date()`"
output: html_document
---

```{r Read in Sports File}
##Load tidyverse**

library(tidyverse)

##Load csv and create a dataframe and add leading zeros to campus number

Sports <- read.csv('Sports_Native.csv', stringsAsFactors = FALSE, header = TRUE) %>%
  mutate(campus_number = sprintf("%03d", campus_number))

#Create structure to include all campuses regardless of programmed offered
  all_campuses <- Sports %>% distinct(campus_number)
```

```{r Baseball}
## Subset of data file

Baseball <- Sports[, c("campus_number", "baseball")]

####

Baseball <- Baseball %>%
  mutate(baseball = str_replace_all(baseball, c("1" = "sports_club_boys-Baseball", "2" = "sports_uil_boys-Baseball", "3" = "sports_club_girls-Baseball", "4" = "sports_uil_girls-Baseball", "5" = "sports_club_coed-Baseball", "6" = "sports_uil_coed-Baseball", "-99" = "NA")))
  

Baseball_final <- Baseball %>% mutate(ind = Baseball$campus_number) %>%
  separate_rows(baseball, sep=",") 

### rename column 1 to "entitiy_id"

names(Baseball_final)[1] <- "entity_id"


Baseball_final[c('type', 'value')] <- str_split_fixed(Baseball_final$baseball, '-', 2)

### remove zeros from 'value' and NA from 'type'

Baseball_final <-filter(Baseball_final, type!='NA')
  

### remove unneeded columns

Baseball_final$baseball <- NULL

Baseball_final$ind <- NULL


```

```{r Basketball}
## Subset of data file
library(tidyverse)

Basketball <- Sports[, c("campus_number", "basketball")]


Basketball <- Basketball %>%
  mutate(basketball = str_replace_all(basketball, c("1" = "sports_club_boys-Basketball", "2" = "sports_uil_boys-Basketball", "3" = "sports_club_girls-Basketball", "4" = "sports_uil_girls-Basketball", "5" = "sports_club_coed-Basketball", "6" = "sports_uil_coed-Basketball", "-99" = "NA")))
  

Basketball_final <- Basketball %>% mutate(ind = Basketball$campus_number) %>%
  separate_rows(basketball, sep=",") 


### rename column 1 to "entitiy_id"

names(Basketball_final)[1] <- "entity_id"


Basketball_final[c('type', 'value')] <- str_split_fixed(Basketball_final$basketball, '-', 2)

### remove zeros from 'value' and NA from 'type'

Basketball_final <-filter(Basketball_final, type!='NA')
  

### remove unneeded columns

Basketball_final$basketball <- NULL

Basketball_final$ind <- NULL


```

```{r Cheer_Drill}
## Subset of data file
library(tidyverse)

Cheer_drill <- Sports[, c("campus_number", "cheer_drill")]


Cheer_drill <- Cheer_drill %>%
  mutate(cheer_drill = str_replace_all(cheer_drill, c("1" = "sports_club_boys-Cheer/Drill", "2" = "sports_uil_boys-Cheer/Drill", "3" = "sports_club_girls-Cheer/Drill", "4" = "sports_uil_girls-Cheer/Drill", "5" = "sports_club_coed-Cheer/Drill", "6" = "sports_uil_coed-Cheer/Drill", "-99" = "NA")))
  

Cheer_drill_final <- Cheer_drill %>% mutate(ind = Cheer_drill$campus_number) %>%
  separate_rows(cheer_drill, sep=",") 


### rename column 1 to "entitiy_id"

names(Cheer_drill_final)[1] <- "entity_id"


Cheer_drill_final[c('type', 'value')] <- str_split_fixed(Cheer_drill_final$cheer_drill, '-', 2)

### remove zeros from 'value' and NA from 'type'

Cheer_drill_final <-filter(Cheer_drill_final, type!='NA')
  

### remove unneeded columns

Cheer_drill_final$cheer_drill <- NULL

Cheer_drill_final$ind <- NULL

### install and load writexl package


```

```{r Cross_country}
## Subset of data file
library(tidyverse)

Cross_country <- Sports[, c("campus_number", "cross_country")]


Cross_country <- Cross_country %>%
  mutate(cross_country = str_replace_all(cross_country, c("1" = "sports_club_boys-Cross Country", "2" = "sports_uil_boys-Cross Country", "3" = "sports_club_girls-Cross Country", "4" = "sports_uil_girls-Cross Country", "5" = "sports_club_coed-Cross Country", "6" = "sports_uil_coed-Cross Country", "-99" = "NA")))
  

Cross_country_final <- Cross_country %>% mutate(ind = Cross_country$campus_number) %>%
  separate_rows(cross_country, sep=",") 


### rename column 1 to "entitiy_id"

names(Cross_country_final)[1] <- "entity_id"


Cross_country_final[c('type', 'value')] <- str_split_fixed(Cross_country_final$cross_country, '-', 2)

### remove zeros from 'value' and NA from 'type'

Cross_country_final <-filter(Cross_country_final, type!='NA')
  

### remove unneeded columns

Cross_country_final$cross_country <- NULL

Cross_country_final$ind <- NULL


```

```{r Football}
## Subset of data file
library(tidyverse)

Football <- Sports[, c("campus_number", "football")]



Football <- Football %>%
  mutate(football = str_replace_all(football, c("1" = "sports_club_boys-Football", "2" = "sports_uil_boys-Football", "3" = "sports_club_girls-Football", "4" = "sports_uil_girls-Football", "5" = "sports_club_coed-Football", "6" = "sports_uil_coed-Football", "-99" = "NA")))
  

Football_final <- Football %>% mutate(ind = Football$campus_number) %>%
  separate_rows(football, sep=",") 


### rename column 1 to "entitiy_id"

names(Football_final)[1] <- "entity_id"


Football_final[c('type', 'value')] <- str_split_fixed(Football_final$football, '-', 2)

### remove zeros from 'value' and NA from 'type'

Football_final <-filter(Football_final, type!='NA')
  

### remove unneeded columns

Football_final$football <- NULL

Football_final$ind <- NULL

```

```{r Golf}
## Subset of data file
library(tidyverse)

Golf <- Sports[, c("campus_number", "golf")]


Golf <- Golf %>%
  mutate(golf = str_replace_all(golf, c("1" = "sports_club_boys-Golf", "2" = "sports_uil_boys-Golf", "3" = "sports_club_girls-Golf", "4" = "sports_uil_girls-Golf", "5" = "sports_club_coed-Golf", "6" = "sports_uil_coed-Golf", "-99" = "NA")))
  

Golf_final <- Golf %>% mutate(ind = Golf$campus_number) %>%
  separate_rows(golf, sep=",") 


### rename column 1 to "entitiy_id"

names(Golf_final)[1] <- "entity_id"


Golf_final[c('type', 'value')] <- str_split_fixed(Golf_final$golf, '-', 2)

### remove zeros from 'value' and NA from 'type'

Golf_final <-filter(Golf_final, type!='NA')
  

### remove unneeded columns

Golf_final$golf <- NULL

Golf_final$ind <- NULL

```

```{r Soccer}
## Subset of data file
library(tidyverse)

Soccer <- Sports[, c("campus_number", "soccer")]

##

Soccer <- Soccer %>%
  mutate(soccer = str_replace_all(soccer, c("1" = "sports_club_boys-Cheer/Drill", "2" = "sports_uil_boys-Cheer/Drill", "3" = "sports_club_girls-Cheer/Drill", "4" = "sports_uil_girls-Cheer/Drill", "5" = "sports_club_coed-Cheer/Drill", "6" = "sports_uil_coed-Cheer/Drill", "-99" = "NA")))
  

Soccer_final <- Soccer %>% mutate(ind = Soccer$campus_number) %>%
  separate_rows(soccer, sep=",") 


### rename column 1 to "entitiy_id"

names(Soccer_final)[1] <- "entity_id"


Soccer_final[c('type', 'value')] <- str_split_fixed(Soccer_final$soccer, '-', 2)

### remove zeros from 'value' and NA from 'type'

Soccer_final <-filter(Soccer_final, type!='NA')
  

### remove unneeded columns

Soccer_final$soccer <- NULL

Soccer_final$ind <- NULL

```

```{r Softball}
## Subset of data file
library(tidyverse)

Softball <- Sports[, c("campus_number", "softball")]


Softball <- Softball %>%
  mutate(softball = str_replace_all(softball, c("1" = "sports_club_boys-Softball", "2" = "sports_uil_boys-Softball", "3" = "sports_club_girls-Softball", "4" = "sports_uil_girls-Softball", "5" = "sports_club_coed-Softball", "6" = "sports_uil_coed-Softball", "-99" = "NA")))
  

Softball_final <- Softball %>% mutate(ind = Softball$campus_number) %>%
  separate_rows(softball, sep=",") 


### rename column 1 to "entitiy_id"

names(Softball_final)[1] <- "entity_id"


Softball_final[c('type', 'value')] <- str_split_fixed(Softball_final$softball, '-', 2)

### remove zeros from 'value' and NA from 'type'

Softball_final <-filter(Softball_final, type!='NA')
  

### remove unneeded columns

Softball_final$softball <- NULL

Softball_final$ind <- NULL

```

```{r Swim}
## Subset of data file
library(tidyverse)

Swim <- Sports[, c("campus_number", "swim")]

##

Swim <- Swim %>%
  mutate(swim = str_replace_all(swim, c("1" = "sports_club_boys-Swimming/Diving", "2" = "sports_uil_boys-Swimming/Diving", "3" = "sports_club_girls-Swimming/Diving", "4" = "sports_uil_girls-Swimming/Diving", "5" = "sports_club_coed-Swimming/Diving", "6" = "sports_uil_coed-Swimming/Diving", "-99" = "NA")))
  

Swim_final <- Swim %>% mutate(ind = Swim$campus_number) %>%
  separate_rows(swim, sep=",") 


### rename column 1 to "entitiy_id"

names(Swim_final)[1] <- "entity_id"


Swim_final[c('type', 'value')] <- str_split_fixed(Swim_final$swim, '-', 2)

### remove zeros from 'value' and NA from 'type'

Swim_final <-filter(Swim_final, type!='NA')
  

### remove unneeded columns

Swim_final$swim <- NULL

Swim_final$ind <- NULL

```

```{r Team_tennis}
## Subset of data file
library(tidyverse)

Team_tennis <- Sports[, c("campus_number", "team_tennis")]


Team_tennis <- Team_tennis %>%
  mutate(team_tennis = str_replace_all(team_tennis, c("1" = "sports_club_boys-Cheer/Drill", "2" = "sports_uil_boys-Cheer/Drill", "3" = "sports_club_girls-Cheer/Drill", "4" = "sports_uil_girls-Cheer/Drill", "5" = "sports_club_coed-Cheer/Drill", "6" = "sports_uil_coed-Cheer/Drill", "-99" = "NA")))
  

Team_tennis_final <- Team_tennis %>% mutate(ind = Team_tennis$campus_number) %>%
  separate_rows(team_tennis, sep=",") 


### rename column 1 to "entitiy_id"

names(Team_tennis_final)[1] <- "entity_id"


Team_tennis_final[c('type', 'value')] <- str_split_fixed(Team_tennis_final$team_tennis, '-', 2)

### remove zeros from 'value' and NA from 'type'

Team_tennis_final <-filter(Team_tennis_final, type!='NA')
  

### remove unneeded columns

Team_tennis_final$team_tennis <- NULL

Team_tennis_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Team_tennis_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Team_tennis_final.xlsx')

```

```{r Tennis}
## Subset of data file
library(tidyverse)

Tennis <- Sports[, c("campus_number", "tennis")]

##

Tennis <- Tennis %>%
  mutate(tennis = str_replace_all(tennis, c("1" = "sports_club_boys-Tennis", "2" = "sports_uil_boys-Tennis", "3" = "sports_club_girls-Tennis", "4" = "sports_uil_girls-Tennis", "5" = "sports_club_coed-Tennis", "6" = "sports_uil_coed-Tennis", "-99" = "NA")))
  

Tennis_final <- Tennis %>% mutate(ind = Tennis$campus_number) %>%
  separate_rows(tennis, sep=",") 


### rename column 1 to "entitiy_id"

names(Tennis_final)[1] <- "entity_id"


Tennis_final[c('type', 'value')] <- str_split_fixed(Tennis_final$tennis, '-', 2)

### remove zeros from 'value' and NA from 'type'

Tennis_final <-filter(Tennis_final, type!='NA')
  

### remove unneeded columns

Tennis_final$tennis <- NULL

Tennis_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Tennis_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Tennis_final.xlsx')

```

```{r Track}
## Subset of data file
library(tidyverse)

Track <- Sports[, c("campus_number", "track")]

##

Track <- Track %>%
  mutate(track = str_replace_all(track, c("1" = "sports_club_boys-Track/Field", "2" = "sports_uil_boys-Track/Field", "3" = "sports_club_girls-Track/Field", "4" = "sports_uil_girls-Track/Field", "5" = "sports_club_coed-Track/Field", "6" = "sports_uil_coed-Track/Field", "-99" = "NA")))
  

Track_final <- Track %>% mutate(ind = Track$campus_number) %>%
  separate_rows(track, sep=",") 


### rename column 1 to "entitiy_id"

names(Track_final)[1] <- "entity_id"


Track_final[c('type', 'value')] <- str_split_fixed(Track_final$track, '-', 2)

### remove zeros from 'value' and NA from 'type'

Track_final <-filter(Track_final, type!='NA')
  

### remove unneeded columns

Track_final$track <- NULL

Track_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Track_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Track_final.xlsx')

```

```{r Volleyball}
## Subset of data file
library(tidyverse)

Volleyball <- Sports[, c("campus_number", "volley")]

##

Volleyball <- Volleyball %>%
  mutate(volley = str_replace_all(volley, c("1" = "sports_club_boys-Volleyball", "2" = "sports_uil_boys-Volleyball", "3" = "sports_club_girls-Volleyball", "4" = "sports_uil_girls-Volleyball", "5" = "sports_club_coed-Volleyball", "6" = "sports_uil_coed-Volleyball", "-99" = "NA")))
  

Volleyball_final <- Volleyball %>% mutate(ind = Volleyball$campus_number) %>%
  separate_rows(volley, sep=",") 


### rename column 1 to "entitiy_id"

names(Volleyball_final)[1] <- "entity_id"


Volleyball_final[c('type', 'value')] <- str_split_fixed(Volleyball_final$volley, '-', 2)

### remove zeros from 'value' and NA from 'type'

Volleyball_final <-filter(Volleyball_final, type!='NA')
  

### remove unneeded columns

Volleyball_final$volley <- NULL

Volleyball_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Volleyball_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Volleyball_final.xlsx')

```

```{r Water_polo}
## Subset of data file
library(tidyverse)

Water_polo <- Sports[, c("campus_number", "water_polo")]

##

Water_polo <- Water_polo %>%
  mutate(water_polo = str_replace_all(water_polo, c("1" = "sports_club_boys-Water Polo", "2" = "sports_uil_boys-Water Polo", "3" = "sports_club_girls-Water Polo", "4" = "sports_uil_girls-Water Polo", "5" = "sports_club_coed-Water Polo", "6" = "sports_uil_coed-Water Polo", "-99" = "NA")))
  

Water_polo_final <- Water_polo %>% mutate(ind = Water_polo$campus_number) %>%
  separate_rows(water_polo, sep=",") 


### rename column 1 to "entitiy_id"

names(Water_polo_final)[1] <- "entity_id"


Water_polo_final[c('type', 'value')] <- str_split_fixed(Water_polo_final$water_polo, '-', 2)

### remove zeros from 'value' and NA from 'type'

Water_polo_final <-filter(Water_polo_final, type!='NA')
  

### remove unneeded columns

Water_polo_final$water_polo <- NULL

Water_polo_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Water_polo_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Water_polo_final.xlsx')

```

```{r Wrestling}
## Subset of data file
library(tidyverse)

Wrestling <- Sports[, c("campus_number", "wrestling")]

##

Wrestling <- Wrestling %>%
  mutate(wrestling = str_replace_all(wrestling, c("1" = "sports_club_boys-Wrestling", "2" = "sports_uil_boys-Wrestling", "3" = "sports_club_girls-Wrestling", "4" = "sports_uil_girls-Wrestling", "5" = "sports_club_coed-Wrestling", "6" = "sports_uil_coed-Wrestling", "-99" = "NA")))
  

Wrestling_final <- Wrestling %>% mutate(ind = Wrestling$campus_number) %>%
  separate_rows(wrestling, sep=",") 


### rename column 1 to "entitiy_id"

names(Wrestling_final)[1] <- "entity_id"


Wrestling_final[c('type', 'value')] <- str_split_fixed(Wrestling_final$wrestling, '-', 2)

### remove zeros from 'value' and NA from 'type'

Wrestling_final <-filter(Wrestling_final, type!='NA')
  

### remove unneeded columns

Wrestling_final$wrestling <- NULL

Wrestling_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Wrestling_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Wrestling_final.xlsx')

```

```{r Archery}
## Subset of data file
library(tidyverse)

Archery <- Sports[, c("campus_number", "archery")]

##

Archery <- Archery %>%
  mutate(archery = str_replace_all(archery, c("1" = "sports_club_boys-Archery",  "2" = "sports_club_girls-Archery", "3" = "sports_club_coed-Archery", "-99" = "NA")))
  

Archery_final <- Archery %>% mutate(ind = Archery$campus_number) %>%
  separate_rows(archery, sep=",") 


### rename column 1 to "entitiy_id"

names(Archery_final)[1] <- "entity_id"


Archery_final[c('type', 'value')] <- str_split_fixed(Archery_final$archery, '-', 2)

### remove zeros from 'value' and NA from 'type'

Archery_final <-filter(Archery_final, type!='NA')
  

### remove unneeded columns

Archery_final$archery <- NULL

Archery_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Archery_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Archery_final.xlsx')

```

```{r Bowling}
## Subset of data file
library(tidyverse)

Bowling <- Sports[, c("campus_number", "bowling")]

##

Bowling <- Bowling %>%
  mutate(bowling = str_replace_all(bowling, c("1" = "sports_club_boys-Bowling",  "2" = "sports_club_girls-Bowling", "3" = "sports_club_coed-Bowling", "-99" = "NA")))
  

Bowling_final <- Bowling %>% mutate(ind = Bowling$campus_number) %>%
  separate_rows(bowling, sep=",") 


### rename column 1 to "entitiy_id"

names(Bowling_final)[1] <- "entity_id"


Bowling_final[c('type', 'value')] <- str_split_fixed(Bowling_final$bowling, '-', 2)

### remove zeros from 'value' and NA from 'type'

Bowling_final <-filter(Bowling_final, type!='NA')
  

### remove unneeded columns

Bowling_final$bowling <- NULL

Bowling_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Bowling_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Bowling_final.xlsx')

```

```{r Capoiera}
## Subset of data file
library(tidyverse)

Capoiera <- Sports[, c("campus_number", "capoiera")]

##

Capoiera <- Capoiera %>%
  mutate(capoiera = str_replace_all(capoiera, c("1" = "sports_club_boys-Capoiera",  "2" = "sports_club_girls-Capoiera", "3" = "sports_club_coed-Capoiera", "-99" = "NA")))
  

Capoiera_final <- Capoiera %>% mutate(ind = Capoiera$campus_number) %>%
  separate_rows(capoiera, sep=",") 


### rename column 1 to "entitiy_id"

names(Capoiera_final)[1] <- "entity_id"


Capoiera_final[c('type', 'value')] <- str_split_fixed(Capoiera_final$capoiera, '-', 2)

### remove zeros from 'value' and NA from 'type'

Capoiera_final <-filter(Capoiera_final, type!='NA')
  

### remove unneeded columns

Capoiera_final$capoiera <- NULL

Capoiera_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Capoiera_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Capoiera_final.xlsx')

```

```{r Disc_golf}
## Subset of data file
library(tidyverse)

Disc_golf <- Sports[, c("campus_number", "disc_golf")]

##

Disc_golf <- Disc_golf %>%
  mutate(disc_golf = str_replace_all(disc_golf, c("1" = "sports_club_boys-Disc Golf",  "2" = "sports_club_girls-Disc Golf", "3" = "sports_club_coed-Disc Golf", "-99" = "NA")))
  

Disc_golf_final <- Disc_golf %>% mutate(ind = Disc_golf$campus_number) %>%
  separate_rows(disc_golf, sep=",") 


### rename column 1 to "entitiy_id"

names(Disc_golf_final)[1] <- "entity_id"


Disc_golf_final[c('type', 'value')] <- str_split_fixed(Disc_golf_final$disc_golf, '-', 2)

### remove zeros from 'value' and NA from 'type'

Disc_golf_final <-filter(Disc_golf_final, type!='NA')
  

### remove unneeded columns

Disc_golf_final$disc_golf <- NULL

Disc_golf_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Disc_golf_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Disc_golf_final.xlsx')

```

```{r Flag_football}
## Subset of data file
library(tidyverse)

Flag_football <- Sports[, c("campus_number", "flag_football")]

##

Flag_football <- Flag_football %>%
  mutate(flag_football = str_replace_all(flag_football, c("1" = "sports_club_boys-Flag Football",  "2" = "sports_club_girls-Flag Football", "3" = "sports_club_coed-Flag Football", "-99" = "NA")))
  

Flag_football_final <- Flag_football %>% mutate(ind = Flag_football$campus_number) %>%
  separate_rows(flag_football, sep=",") 


### rename column 1 to "entitiy_id"

names(Flag_football_final)[1] <- "entity_id"


Flag_football_final[c('type', 'value')] <- str_split_fixed(Flag_football_final$flag_football, '-', 2)

### remove zeros from 'value' and NA from 'type'

Flag_football_final <-filter(Flag_football_final, type!='NA')
  

### remove unneeded columns

Flag_football_final$flag_football <- NULL

Flag_football_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Flag_football_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Flag_football_final.xlsx')

```

```{r Fun_fit}
## Subset of data file
library(tidyverse)

Fun_fit <- Sports[, c("campus_number", "fun_fit")]

##

Fun_fit <- Fun_fit %>%
  mutate(fun_fit = str_replace_all(fun_fit, c("1" = "sports_club_boys-Fun Fit",  "2" = "sports_club_girls-Fun Fit", "3" = "sports_club_coed-Fun Fit", "-99" = "NA")))
  

Fun_fit_final <- Fun_fit %>% mutate(ind = Fun_fit$campus_number) %>%
  separate_rows(fun_fit, sep=",") 


### rename column 1 to "entitiy_id"

names(Fun_fit_final)[1] <- "entity_id"


Fun_fit_final[c('type', 'value')] <- str_split_fixed(Fun_fit_final$fun_fit, '-', 2)

### remove zeros from 'value' and NA from 'type'

Fun_fit_final <-filter(Fun_fit_final, type!='NA')
  

### remove unneeded columns

Fun_fit_final$fun_fit <- NULL

Fun_fit_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Fun_fit_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Fun_fit_final.xlsx')

```

```{r Gymnastics}
## Subset of data file
library(tidyverse)

Gymnastics <- Sports[, c("campus_number", "gymnastics")]

##

Gymnastics <- Gymnastics %>%
  mutate(gymnastics = str_replace_all(gymnastics, c("1" = "sports_club_boys-Gymnastics",  "2" = "sports_club_girls-Gymnastics", "3" = "sports_club_coed-Gymnastics", "-99" = "NA")))
  

Gymnastics_final <- Gymnastics %>% mutate(ind = Gymnastics$campus_number) %>%
  separate_rows(gymnastics, sep=",") 


### rename column 1 to "entitiy_id"

names(Gymnastics_final)[1] <- "entity_id"


Gymnastics_final[c('type', 'value')] <- str_split_fixed(Gymnastics_final$gymnastics, '-', 2)

### remove zeros from 'value' and NA from 'type'

Gymnastics_final <-filter(Gymnastics_final, type!='NA')
  

### remove unneeded columns

Gymnastics_final$gymnastics <- NULL

Gymnastics_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Gymnastics_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Gymnastics_final.xlsx')

```

```{r Karate}
## Subset of data file
library(tidyverse)

Karate <- Sports[, c("campus_number", "karate")]

##

Karate <- Karate %>%
  mutate(karate = str_replace_all(karate, c("1" = "sports_club_boys-Karate",  "2" = "sports_club_girls-Karate", "3" = "sports_club_coed-Karate", "-99" = "NA")))
  

Karate_final <- Karate %>% mutate(ind = Karate$campus_number) %>%
  separate_rows(karate, sep=",") 


### rename column 1 to "entitiy_id"

names(Karate_final)[1] <- "entity_id"


Karate_final[c('type', 'value')] <- str_split_fixed(Karate_final$karate, '-', 2)

### remove zeros from 'value' and NA from 'type'

Karate_final <-filter(Karate_final, type!='NA')
  

### remove unneeded columns

Karate_final$karate <- NULL

Karate_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Karate_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Karate_final.xlsx')

```

```{r Lacrosse}
## Subset of data file
library(tidyverse)

Lacrosse <- Sports[, c("campus_number", "lacrosse")]

##

Lacrosse <- Lacrosse %>%
  mutate(lacrosse = str_replace_all(lacrosse, c("1" = "sports_club_boys-Lacrosse",  "2" = "sports_club_girls-Lacrosse", "3" = "sports_club_coed-Lacrosse", "-99" = "NA")))
  

Lacrosse_final <- Lacrosse %>% mutate(ind = Lacrosse$campus_number) %>%
  separate_rows(lacrosse, sep=",") 


### rename column 1 to "entitiy_id"

names(Lacrosse_final)[1] <- "entity_id"


Lacrosse_final[c('type', 'value')] <- str_split_fixed(Lacrosse_final$lacrosse, '-', 2)

### remove zeros from 'value' and NA from 'type'

Lacrosse_final <-filter(Lacrosse_final, type!='NA')
  

### remove unneeded columns

Lacrosse_final$lacrosse <- NULL

Lacrosse_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Lacrosse_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Lacrosse_final.xlsx')

```

```{r Running}
## Subset of data file
library(tidyverse)

Running <- Sports[, c("campus_number", "running")]

##

Running <- Running %>%
  mutate(running = str_replace_all(running, c("1" = "sports_club_boys-Running",  "2" = "sports_club_girls-Running", "3" = "sports_club_coed-Running", "-99" = "NA")))
  

Running_final <- Running %>% mutate(ind = Running$campus_number) %>%
  separate_rows(running, sep=",") 


### rename column 1 to "entitiy_id"

names(Running_final)[1] <- "entity_id"


Running_final[c('type', 'value')] <- str_split_fixed(Running_final$running, '-', 2)

### remove zeros from 'value' and NA from 'type'

Running_final <-filter(Running_final, type!='NA')
  

### remove unneeded columns

Running_final$running <- NULL

Running_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Running_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Running_final.xlsx')

```

```{r Squash}
## Subset of data file
library(tidyverse)

Squash <- Sports[, c("campus_number", "squash")]

##

Squash <- Squash %>%
  mutate(squash = str_replace_all(squash, c("1" = "sports_club_boys-Squash",  "2" = "sports_club_girls-Squash", "3" = "sports_club_coed-Squash", "-99" = "NA")))
  

Squash_final <- Squash %>% mutate(ind = Squash$campus_number) %>%
  separate_rows(squash, sep=",") 


### rename column 1 to "entitiy_id"

names(Squash_final)[1] <- "entity_id"


Squash_final[c('type', 'value')] <- str_split_fixed(Squash_final$squash, '-', 2)

### remove zeros from 'value' and NA from 'type'

Squash_final <-filter(Squash_final, type!='NA')
  

### remove unneeded columns

Squash_final$squash <- NULL

Squash_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Squash_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Squash_final.xlsx')

```

```{r Strength}
## Subset of data file
library(tidyverse)

Strength <- Sports[, c("campus_number", "strength")]

##

Strength <- Strength %>%
  mutate(strength = str_replace_all(strength, c("1" = "sports_club_boys-Strength/Conditioning",  "2" = "sports_club_girls-Strength/Conditioning", "3" = "sports_club_coed-Strength/Conditioning", "-99" = "NA")))
  

Strength_final <- Strength %>% mutate(ind = Strength$campus_number) %>%
  separate_rows(strength, sep=",") 


### rename column 1 to "entitiy_id"

names(Strength_final)[1] <- "entity_id"


Strength_final[c('type', 'value')] <- str_split_fixed(Strength_final$strength, '-', 2)

### remove zeros from 'value' and NA from 'type'

Strength_final <-filter(Strength_final, type!='NA')
  

### remove unneeded columns

Strength_final$strength <- NULL

Strength_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Strength_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Strength_final.xlsx')

```

```{r Yoga}
## Subset of data file
library(tidyverse)

Yoga <- Sports[, c("campus_number", "yoga")]

##

Yoga <- Yoga %>%
  mutate(yoga = str_replace_all(yoga, c("1" = "sports_club_boys-Yoga",  "2" = "sports_club_girls-Yoga", "3" = "sports_club_coed-Yoga", "-99" = "NA")))
  

Yoga_final <- Yoga %>% mutate(ind = Yoga$campus_number) %>%
  separate_rows(yoga, sep=",") 


### rename column 1 to "entitiy_id"

names(Yoga_final)[1] <- "entity_id"


Yoga_final[c('type', 'value')] <- str_split_fixed(Yoga_final$yoga, '-', 2)

### remove zeros from 'value' and NA from 'type'

Yoga_final <-filter(Yoga_final, type!='NA')
  

### remove unneeded columns

Yoga_final$yoga <- NULL

Yoga_final$ind <- NULL

### install and load writexl package

library(writexl)

write_xlsx(Yoga_final, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\Yoga_final.xlsx')

```


```{r All dataframes Union into one File and add an Id column}

All_Sports <- rbind(Archery_final, Baseball_final, Cheer_drill_final, Cross_country_final, Football_final, 
                    Golf_final, Soccer_final, Softball_final, Swim_final, Team_tennis_final, Tennis_final, Track_final,
                    Volleyball_final, Water_polo_final, Wrestling_final, Archery_final, Bowling_final, Capoiera_final,
                    Disc_golf_final, Flag_football_final, Fun_fit_final, Gymnastics_final, Karate_final, Lacrosse_final,
                    Running_final, Squash_final, Strength_final, Yoga_final)


names(All_Sports)[1] <-"entity_id" 

names(all_campuses)[1] <- "entity_id"

### join with all_campuses to create final list
All_Sports <- left_join(all_campuses, All_Sports, by = "entity_id")


All_Sports <-All_Sports %>%
 mutate(value = ifelse(is.na(value), "Sports Not Offered", value), 
        type = ifelse(is.na(type), "sports", type))

All_Sports[, "id"] <-""
 
#### All_Sports$index <- 1:nrow(All_Sports)  ####

####    names(All_Sports)[4] <- "id" ####

### install and load writexl package

library(writexl)

write_xlsx(All_Sports, 'R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\All_Sports.xlsx')


write.csv(All_Sports, "R:\\Specialists Transfer\\Ken\\GitHub\\Schoolfinder_Sports\\All_Sports_final_id.csv", row.names=FALSE)
```












